# Generated by Django 5.1.1 on 2024-10-05 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='icon_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
