# Use an official Python runtime as a parent image
FROM python:3.12.7-slim-bookworm

# Set environment varibles
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# Set work directory
WORKDIR /usr/src/app

# Install dependencies
RUN pip install --upgrade pip
COPY ./requirements.txt /usr/src/app/requirements.txt
COPY ./requirements.dev.txt /usr/src/app/requirements.dev.txt
RUN pip install -r requirements.dev.txt

# Copy project
COPY . /usr/src/app/

# Command to run the application
CMD ["python", "manage.py", "runserver", "127.0.0.1:8000"]