# Generated by Django 5.1.1 on 2024-10-09 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issuer_name', models.CharField(max_length=255)),
                ('instrument_name', models.CharField(max_length=255)),
                ('isin', models.CharField(max_length=12)),
                ('mifir_identifier_code', models.CharField(max_length=10)),
                ('mifir_sub_class_code', models.CharField(max_length=10)),
                ('mifir_sub_class_name', models.CharField(max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('maturity_date', models.DateField(null=True)),
                ('coupon_interest_rate', models.FloatField(null=True)),
                ('country_of_incorporation', models.CharField(max_length=50)),
                ('trading_currency', models.CharField(max_length=3)),
                ('lse_market', models.CharField(max_length=50)),
                ('fca_listing_category', models.CharField(max_length=255, null=True)),
                ('market_segment_code', models.CharField(max_length=10)),
                ('market_sector_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tblBond',
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblBook',
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('alpha_2', models.CharField(max_length=2, unique=True)),
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'db_table': 'tblCountry',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('name', models.CharField(default='GBP', max_length=3, primary_key=True, serialize=False)),
                ('gbp_value', models.FloatField(default=1)),
            ],
            options={
                'db_table': 'tbleCurrency',
            },
        ),
        migrations.CreateModel(
            name='Equity',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issuer_name', models.CharField(max_length=255)),
                ('instrument_name', models.CharField(max_length=255)),
                ('isin', models.CharField(max_length=12)),
                ('mifir_identifier_code', models.CharField(max_length=255)),
                ('icb_industry', models.CharField(max_length=255)),
                ('icb_super_sector', models.CharField(max_length=255)),
                ('start_date', models.DateField(null=True)),
                ('country_of_incorporation', models.CharField(max_length=50)),
                ('trading_currency', models.CharField(max_length=3)),
                ('mkt_cap_mm', models.FloatField(null=True)),
                ('lse_market', models.CharField(max_length=50)),
                ('fca_listing_category', models.CharField(max_length=255, null=True)),
                ('market_segment_code', models.CharField(max_length=10)),
                ('market_sector_code', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Equities',
                'db_table': 'tblEquity',
            },
        ),
        migrations.CreateModel(
            name='Etp',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('issuer_name', models.CharField(max_length=255)),
                ('instrument_name', models.CharField(max_length=255)),
                ('isin', models.CharField(max_length=12)),
                ('mifir_identifier_code', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('country_of_incorporation', models.CharField(max_length=50)),
                ('trading_currency', models.CharField(max_length=3)),
                ('lse_market', models.CharField(max_length=50)),
                ('fca_listing_category', models.CharField(max_length=255, null=True)),
                ('market_segment_code', models.CharField(max_length=10)),
                ('market_sector_code', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'tblEtp',
            },
        ),
        migrations.CreateModel(
            name='MonthlyVolume',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=12)),
                ('gbp_turnover', models.FloatField(null=True)),
                ('number_of_trades', models.IntegerField()),
                ('volume', models.FloatField(null=True)),
                ('avg_trade_size', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'tblMonthlyVolume',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblPortfolio',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblRegion',
            },
        ),
        migrations.CreateModel(
            name='TradingView',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('description', models.CharField(max_length=255)),
                ('technical_rating', models.CharField(max_length=25)),
                ('oscillators_rating', models.CharField(max_length=25)),
                ('moving_avg_rating', models.CharField(max_length=25)),
                ('price', models.FloatField(null=True)),
                ('perf_weekly', models.FloatField(null=True)),
                ('perf_monthly', models.FloatField(null=True)),
                ('perf_3m', models.FloatField(null=True)),
                ('perf_ytd', models.FloatField(null=True)),
                ('perf_6m', models.FloatField(null=True)),
                ('vol_1w', models.FloatField(null=True)),
                ('vol_1m', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'tblTradingview',
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('id', models.CharField(max_length=4, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'tblWatchlist',
            },
        ),
        migrations.CreateModel(
            name='WeeklyVolume',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('isin', models.CharField(max_length=12)),
                ('gbp_turnover', models.FloatField(null=True)),
                ('number_of_trades', models.IntegerField()),
                ('avg_spread', models.FloatField(null=True)),
                ('avg_trade_size', models.FloatField(null=True)),
            ],
            options={
                'db_table': 'tblWeeklyVolume',
            },
        ),
        migrations.CreateModel(
            name='CurrentInvestment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('qty', models.PositiveIntegerField(null=True)),
                ('avg_px', models.FloatField()),
                ('current_px', models.FloatField()),
                ('book', models.ForeignKey(db_column='book', on_delete=django.db.models.deletion.CASCADE, to='investment.book')),
                ('ticker', models.ForeignKey(db_column='ticker', on_delete=django.db.models.deletion.CASCADE, to='investment.etp')),
            ],
            options={
                'db_table': 'tblCurrentInvestment',
            },
        ),
        migrations.CreateModel(
            name='SubRegion',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.region')),
            ],
            options={
                'db_table': 'tblSubRegion',
            },
        ),
        migrations.CreateModel(
            name='ManualMeta',
            fields=[
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('ticker', models.CharField(max_length=45, primary_key=True, serialize=False)),
                ('asset_class', models.CharField(max_length=25)),
                ('objective', models.CharField(max_length=50)),
                ('emerging_mkt', models.BooleanField(default=False)),
                ('leverage_typ', models.CharField(max_length=10, null=True)),
                ('hedge_ccy', models.CharField(max_length=5, null=True)),
                ('single_stock', models.BooleanField(default=False)),
                ('country', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.country')),
                ('region', models.ForeignKey(blank=True, default='Global', null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.region')),
                ('sub_region', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='investment.subregion')),
            ],
            options={
                'db_table': 'tblManualMeta',
            },
        ),
        migrations.AddField(
            model_name='country',
            name='subregion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='investment.subregion'),
        ),
    ]
